services:
  - type: web
    runtime: python
    name: voyager-status
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y chromium-chromedriver
      pip install -r requirements.txt
    startCommand: waitress-serve --port $PORT --call 'app:create_app'
    envVars:
      - key: CHROMEDRIVER_PATH
        value: /usr/bin/chromedriver
      - key: GOOGLE_CHROME_BIN
        value: /usr/bin/google-chrome
