services:
  - type: web
    runtime: python
    name: voyager-status
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y wget unzip
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      apt-get install -y ./google-chrome-stable_current_amd64.deb
      wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/90.0.4430.24/chromedriver_linux64.zip
      unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/
      pip install -r requirements.txt
    startCommand: waitress-serve --port $PORT app:app
    envVars:
      - key: CHROME_BIN
        value: /usr/bin/google-chrome
      - key: CHROMEDRIVER_PATH
        value: /usr/local/bin/chromedriver
